<?php

Class DbSettings {
    
    // ########################################
    // DEFINE DATABASE SETTINGS HERE
    public $db_host = "localhost";
    public $db_name = "simpleleague";
    public $db_user = "root";
    public $db_pass = "";
    // ######################################## 
    
}

Class Settings {
    
    // ########################################
    // DEFINE LABELS HERE
    // (will be displayed in HTML tables)
    public $label_player = "Player";
    public $label_season = "Season";
    public $label_team = "Team";
    public $label_round = "Round";
    public $label_vs = "vs.";
    public $label_nogame = "no game";
    public $label_points = "Points";
    public $label_victorypoints = "Victory Points";
    public $label_victorypoints_difference = "Diff.";
    public $label_point_separator = ":";
    public $label_result = "Result";
    public $label_number_of_games = "No. of games";
    public $label_crosstab_home = "Home";
    public $label_crosstab_guest = "Guest";
    // ########################################
    
    // ########################################
    // OTHER SETTINGS
    // Properties for HTML tables, will be put into the <table> tag
    public $html_table_properties = "border='1'";
    // additional properties for "schedule per season" table:
    public $html_schedule_table_properties = "style='width:250px'";
    
    // properties for headline row in each table
    public $html_table_headline_properties = "style='font-weight:bold;'";
    
    // cross table, background color for headlines
    public $html_crosstab_headline_bgcolor = "lightgrey";
    
    // header and footer (will be displayed above and below each table)
    public $html_header = "<br>";
    public $html_footer = "<br>";
    
    // ########################################
    // "Generated by" text (will be displayed in HTML comment above each table)
    public $generated_by = "Table generated by SimpleLeague (http://christianspecht.de/simpleleague/)";
    // ########################################
}


// ################################################################################
// Optional: custom callback function for escaping double-mustache variables.
// Defaults to htmlspecialchars like Mustache.php's default behaviour
// (see https://github.com/bobthecow/mustache.php/wiki#escape)
// You can change it here if you need anything special
// ################################################################################
function custom_escape($value) {
    return htmlspecialchars($value);
}

?>
